### ISSUE TITLE
place of author looks strange, when applet name is really long

### ISSUE THREAD

**Issue by NikoKrause** [clefebvre/cinnamon-spices#11]
Look at this applet:
https://cinnamon-spices.linuxmint.com/applets/view/83

Between name of applet and author there is a big gap:
![screenshot-area-2017-02-13-233415](https://cloud.githubusercontent.com/assets/8415124/22906493/fd84d9fc-f244-11e6-984c-a334214705ab.png)

**Comment by nyrrad** [comment]
Fixed by applying flex-wrap.
