### ISSUE TITLE
horizontal scrolling, when tiled in half

### ISSUE THREAD

**Issue by NikoKrause** [clefebvre/cinnamon-spices#12]
When I tile a window in half I usually get a horizontal scrollbar.
That's not the case for the spices website.

**Comment by nyrrad** [comment]
Scroll bar will be back for now.
Going to implement responsive solution to the tiles on the category pages

**Comment by nyrrad** [comment]
Should be completely fixed.
Pages are now responsive. There is re-flow on the homepage but not high priority.

commit: e37739485d7838d464ab23c84763f44261576e29

**Comment by NikoKrause** [comment]
Much better.
There's a lot space wasted in the buttons though:

![screenshot-window-2017-03-22-192414](https://cloud.githubusercontent.com/assets/8415124/24214245/374c168e-0f35-11e7-9038-18b36428c75e.png)

**Comment by nyrrad** [comment]
ill look into it

**Comment by nyrrad** [comment]
I found whats causing the text wrap, easy fix. It'll be fixed with the next style sync
