### ISSUE TITLE
Invalid description

### ISSUE THREAD

**Issue by NikoKrause** [clefebvre/cinnamon-spices#13]
This applet https://cinnamon-spices.linuxmint.com/applets/view/207 says `Invalid description`

The metadata.json file looks like this:
```js
{ 
    "version": "1.2", 
    "description": "Touches d'invocations personalisées et capture vidéo du bureau en MP4",
    "name": "Transformice helper",
    "uuid": "tfmKeyboard@alexpp"
}
```
Where does that come from? Is it because of the `é` or because of `'` ? It should show them anyway.

**Comment by MrElectroNick** [comment]
@NikoKrause All is about UTF-8 characters in description text. Fix is coming.

**Comment by NikoKrause** [comment]
This seems to be fixed now.

**Comment by NikoKrause** [comment]
Ah. I looked at the wrong applet.

**Comment by NikoKrause** [comment]
But Developer's Tools is showing right now.

**Comment by MrElectroNick** [comment]
@NikoKrause Next time this applet is updated - description will be parsed again. You can do a dummy commit there to refresh it

**Comment by NikoKrause** [comment]
Ah. Ok. No need for a dummy commit. As soon as an translation comes in it will be updated.

**Comment by nyrrad** [comment]
Is this issue resolved then?

**Comment by NikoKrause** [comment]
Yes.

**Comment by MrElectroNick** [comment]
Nice. Finally this applet has been updated :rofl:

**Comment by NikoKrause** [comment]
Yeah, the author has been set to none :)
