### ISSUE TITLE
Feature Request: Add git commit title and description to "Last commit:" 

### ISSUE THREAD

**Issue by Piiit** [clefebvre/cinnamon-spices#2]
Would be nice to have more information under "Last commit:" of each applet etc. on the webpage. Otherwise I have to click each time and go to github to understand what has been done recently. Would be nice to have a short overview of the last commit message and a "read more..." link to github. 

Last commit hash is not meaningful for the regular spices website visitor. I would suggest to remove it completely, or make it smaller or hide it inside a tooltip.

**Comment by nyrrad** [comment]
Hash has been trimmed down to 8chars, commit message now appears on spice pages.
Hash now links to actual commit, not commit tree.
