### ISSUE TITLE
Rating system not working properly

### ISSUE THREAD

**Issue by mdchaves** [clefebvre/cinnamon-spices#21]
Whenever I "like" an applet or extension, its rating is decreased; not increased as anyone would expect. That's probably the reason why many popular applets have lost "stars" lately.

**Comment by Odyseus** [comment]
Hello, @mdchaves.

> Whenever I "like" an applet or extension, its rating is decreased...

That's the intended behavior of the new rating system. See [this blog post](http://blog.linuxmint.com/?p=3199) were it is mentioned (the paragraph just above **Improved security**).

**Comment by mdchaves** [comment]
@Odyseus , I've just tested: Multi Translator had score=5. Then I like it, and now it has score=3. How on Earth can this be an intended behavior? What's the reason for that?

**Comment by Odyseus** [comment]
@mdchaves.

> What's the reason for that?

The reason is in the blog post that I linked above.

**Comment by mdchaves** [comment]
Sorry but the blog post doesn't say anything to that effect. It explains the reason for a new rating system, but obviously it says nothing about a crazy system that remove score when someone upvote an applet. That makes no sense at all.

**Comment by nyrrad** [comment]
@mdchaves,
While @Odyseus is right that there is an inherit decay to the scores, a 2pt drop after hitting the like button confuses me.. I've tried to recreate your experience and haven't been able to yet. The only thing @MrElectroNick and i have been able to deduce is you might have possibly done it during a spice db update or something of the like. We're still looking into the matter.

**Comment by mdchaves** [comment]
@nyrrad I've just tried reproducing it again. So when I "liked" mockturtl's Wheather applet, its score increased from 7 to 8 stars, as I would expect. But when I "liked" the Sticky notes applet, its score decreased from 5 to 3. So apparently the issue doesn't appear always in every applet.

**Comment by clefebvre** [comment]
Votes were counted for a up to a month, this was changed today to a full year.

**Comment by nyrrad** [comment]
Issue seems to be much less now that its more of a yearly decay than monthly
