### ISSUE TITLE
Feature request: ability to format comments on the 'spices' website

### ISSUE THREAD

**Issue by CottonEaster** [clefebvre/cinnamon-spices#24]
Seemingy line breaks and indentation are removed from comments on the spices website - without warning, and without the possibility of editing the comment afterwards. Nor seemingly are italics or bold supported. Can't we have a text box . . like the one I am using to type this? It would be a great improvement.

(This report filed in this repository [onthe advice of NikoKrause](https://github.com/linuxmint/cinnamon-spices-extensions/issues/114#issuecomment-317351414) .)

**Comment by nyrrad** [comment]
It appears line breaks are lost in the initial ajax representation of the comment but are there if you refresh the page as this actually retrieves the comment from the db. Thank you for bringing this to my attention i will look into it and get a fix pushed asap.

 As for the other formatting(colors, text styles), i know Github uses markdown for their comments which might be a bit overkill for the cinnamon-spices website. But i will look into it none the less. 

Will leave this open to reply after i do some research on markdown comment systems

**Comment by nyrrad** [comment]
Line break issue fix has been pushed. Wont be live for a little while though.

**Comment by nyrrad** [comment]
After doing some research on the matter, i think that we're going to forgo the markdown comments for the time being. It opens up xss possibilities that are not worth the gain at the moment. 

With the recent fix to formatting and links being actual hyperlinks and the new issue button being rolled out, there is sufficient functionality for a comment section.
