### ISSUE TITLE
Report bug/issue button, Feature request button

### ISSUE THREAD

**Issue by NikoKrause** [clefebvre/cinnamon-spices#26]
Often saw, that users are reporting bugs or asking for features in the comments of the spices website, e.g. https://cinnamon-spices.linuxmint.com/applets/view/116 or https://cinnamon-spices.linuxmint.com/applets/view/279

Adding a `Bug report`/`Feature request` button to the spices website would possibly make it more obvious for people, where to report bugs to.

I found this site here https://fire.fundersclub.com/, which allows to create GitHub issues via E-Mail.
You need to add fire-bot as a collaborator to the repo and set up an E-Mailaddress.

To test it, I did it with a repo of mine, and that was the result: https://github.com/NikoKrause/CinnVIIStarkMenu/issues/43

If you want to, you can test it also by sending an E-Mail to `nikokrause@fire.fundersclub.com`
The new issue will show up here: https://github.com/NikoKrause/CinnVIIStarkMenu/issues

It even allows E-Mailattachements, so screenshots can be added as well.

The `Bug report` button could open a form on the spices website, which the user has to fill, e.g. asking for the Cinnamon version the user uses, the applet/desklet/extension version, etc. And it can prefill some stuff automatically, e.g. the applets UUID in the title and notifying the author (if exists) in the issues by adding @author at the end of the issue message, adding the facebook/google+/github name of the user, who reported the bug.

When the user has filled the formular, he can press a `Send` button, which sends an E-Mail to the fire-bot. And the bot creates a new issue on the repo.

**Comment by MrElectroNick** [comment]
What if we do an API call to github? Let's say - add a "Report bug" page where user can type in something - then we call GitHub API to add it as issue with proper title format?

**Comment by NikoKrause** [comment]
I don't know how it works with GitHubs API. I found the bot and thought it's pretty easy.

The idea stays the same. The user should see a form, i.e. a "Report bug" page, something like this: ![bla](https://bugdigger.com/tour/bug-report-to-project.gif)

The how is not as important (either by fire-bot or by GitHub API). The fire-bot was only a suggestion.

**Comment by MrElectroNick** [comment]
Ok. I find GitHub API more native way to communicate with it. I'll take a look into that

**Comment by NikoKrause** [comment]
The form should prefill automatically:
- [ ] Spices UUID in the issue title
- [ ] Notify the author by adding @author at the end of the bug report
- [ ] The user, who reports the bug (since he's logged in through Facebook/Google+/GitHub this can be prefilled I guess? I.e. we need some info to contact the user for further informations. If it's a GitHub user that's easy. But if it's a Facebook or Google+ user, we can't contact him in the issue on GitHub itself.)

Required fields:
- [ ] Description of the problem

Optionally:
- [ ] Attachements (png, jpg files or code snippets)
- [ ] Code snippets (so the user can copy e.g. glasslog to this field and it will be formated nicely as a code snippet in markdown)
- [ ] Cinnamon and spices version

@jaszhix Maybe any further ideas?

**Comment by jaszhix** [comment]
I like the idea, I've been responding to a lot of of bug reports in the comment sections encouraging them to submit an issue so we can get more info from them, but often times they don't which is frustrating. I'm for any solution that helps encourage more bug reports.

**Comment by nyrrad** [comment]
Don't you think that could lead to a flooding of issues on the cinnamon-spices-xxxx repos. Especially if they don't get taken care of. It would be helpful if the owners actual repo was preserved in the json file somehow.

**Comment by NikoKrause** [comment]
Users need to login to spices website with their Facebook/Google+/GitHub account to be able to see the `Report bug` button. If they use the button for spam, they can be blocked or we don't show the button for those users anymore (blacklist).

**Comment by nyrrad** [comment]
I didn't mean spam. I just meant a build up of untouched issues. Sorry for the confusion

**Comment by NikoKrause** [comment]
When reporting an issue on launchpad, they tell you to look, if the issue you want to report is already reported. They even show suggestions. Maybe something like this can be considered here. Before you can start to report an issue you get a list of issues belonging to the spice, e.g. a [link to open issue](https://github.com/linuxmint/cinnamon-spices-applets/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20multicore-sys-monitor%40ccadeptic23)

Also it's not possible to delete an issue on GitHub. So we could maybe have a layer between sending an issue on the website and opening an issue on GitHub. The spices reviewers read issue reports anyway. Maybe having a waiting list on the spices website: A list of the issues, which have been reported through this form. If it's a good issue report, the reviewer can accept it and it will be forwarded to GitHub to open an issue. And if it's a bad issue, duplicate or spam, the reviewer refuses the issue report. (And if a user has too many refused issues during a short time, then he can be blocked/blacklisted)

Just some thoughts.

**Comment by nyrrad** [comment]
> When reporting an issue on launchpad, they tell you to look, if the issue you want to report is already reported. They even show suggestions. Maybe something like this can be considered here. Before you can start to report an issue you get a list of issues belonging to the spice, e.g. a link to open issue

This would work perfectly. Having a link on the top of the individual spice page that says "issues" and brings you the the corresponding cinnamon-spices-xxxx repo with the search field filled in with the spice name. We could put a reminder or little message that pops up when they mouse over the issue button to remind them of searching before reporting, being detailed, etc.

As for the layer between the site, that seems like another layer of unnecessary complexity and yet another thing for the repo maintainers to look at, The issue feature is for this very thing. If its a bad/duplicate/spam close it and move on.

**Comment by nyrrad** [comment]
![issue_button](https://user-images.githubusercontent.com/12882579/29497118-09b66c8a-85a8-11e7-9261-2e77c97b9487.png)

Implemented issue button like so. 
Links to corresponding cinnamon-spices-xxxx repo with search field _is:open is:issue uuid_

It may not be perfect but for the time being hopefully it diverts people from posting issues in the comments. Only downside i can see is it forces people to make a github account which might dissuade someone from opening an issue on the proper channel.

**Comment by NikoKrause** [comment]
I talked with collinss about it. He says, that there are mostly 2 kind of people:
1. those who don't know where to post issues
2. those who don't care where to post and you don't get much info from them anyway.

About needing users to create a GitHub when reporting a bug would be probably the best. This way it's assured, that you can contact the user for more info.

I found out, that it's possible to open an issue through URL: https://github.com/linuxmint/cinnamon-spices-applets/issues/new?title=foo&body=bar

But using the `body=bar` overwrites the [ISSUE_TEMPLATE](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/ISSUE_TEMPLATE)

So without `body` it preserves the template:
https://github.com/linuxmint/cinnamon-spices-applets/issues/new?title=foo

But with a URL Encoder you can add the ISSUE_TEMPLATE into the `bar=` URL.

What do you think about the following:
Pressing the issue button, would lead the user to a page, which says: 
* Please check, if the issue you want to report, was already reported -> `A button which links to corresponding cinnamon-spices-xxxx repo with search field is:open is:issue uuid` -> Opens a new tab to this site.
* If your issue hasn't been reported yet -> Another button `File new bug` button.
    * If user is logged in with Facebook/Google+, inform him to create a GitHub account and to log in with that one to the spices website, if he wants to report a bug.
    * Else lead him to https://github.com/linuxmint/cinnamon-spices-applets/issues/new?title=UUID:&body=URL_Encoded_ISSUE_TEMPLATE+@author

**Comment by NikoKrause** [comment]
I like that the `Like button` has a star icon. Would it be too much to add icons to the other buttons too?
E.g. Github icon for `Website`, Arrow down icon for `Download`, and a bug for `Issues` button.

**Comment by NikoKrause** [comment]
P.P.S.: If the number of stars is shown right to the `Like it` button, you don't need the `Score: 0` text below the `UUID` anymore

**Comment by NikoKrause** [comment]
@nyrrad 
I thought about your issue button implementation. I think it suffices. It shows all open (and closed) issues belonging to an applet/desklet etc. And there's also a `New Issue` button right there on GitHub, which says the user to Sign Up, when they don't have a GitHub account. It's simple and doesn't overcomplicate stuff. Lets try this. 

Also together with something like this https://github.com/clefebvre/cinnamon-spices/issues/29, we hopefully miss less comments/issue reports.

**Comment by nyrrad** [comment]
@NikoKrause 
Yea i agree. its simple, concise and uses the tools already there. It'll be even better when all the spices repos have CODEOWNER and ISSUE_TEMPLATE implemented uniformly.

**Comment by NikoKrause** [comment]
The CODEOWNERS is there uniformly for applets/desklets/extensions. There's an open PR for themes (I don't have write access for that). Unfortunately CODEOWNERS works only for users with write access to the repo. I asked a feature request to GitHub to make it work for Contributors or something similar, i.e. so that the user/author/codeowner doesn't need to have write access.

The ISSUE_TEMPLATE is currently only in applets repo iirc. It has changed from time to time, to find out what works best. I saw the Issue template from the Cinnamon repo works pretty well: https://github.com/linuxmint/Cinnamon/blob/master/.github/ISSUE_TEMPLATE.md

I think the template in the applets repo is a little bit overloaded. Adapting the one from the Cinnamon repo might work better.

We can do a uniform template for all spices, though.

**Comment by nyrrad** [comment]
Yea i noticed the CODEOWNERS doesn't work for issues either so thats my fault for not reading into it more. 

As for the ISSUE_TEMPLATE, i agree the applets one is a bit bloated. It could however use an explanation on how to title the issue, Sending them back to the CONTRIBUTING.md to see the title convention seems a bit unnecessary.
