### ISSUE TITLE
Theme previews are huge images

### ISSUE THREAD

**Issue by Piiit** [clefebvre/cinnamon-spices#3]
https://cinnamon-spices.linuxmint.com/git/themes/Blue-mint/screenshot.png for instance is more than 700KB. 

This makes it very slow to load the page.

**Comment by MrElectroNick** [comment]
@Piiit can you recheck please? screenshot.png now only used on any spice details page - not in list. List of themes should load quite fast now

**Comment by Piiit** [comment]
@MrElectroNick Hi, it works great now! However, I noticed another small issue... The Facebook-theme preview on https://cinnamon-spices.linuxmint.com/themes is not loaded. The big preview in details loads correctly.

**Comment by MrElectroNick** [comment]
@Piiit Check again - all previews are showed on my end

**Comment by Piiit** [comment]
@MrElectroNick Hi, I found the issue. It is a problem with Adblock Plus in Firefox... 
There is a filter rule in a default filter list (`/uploads/*facebook.jpg`), that prevents this theme preview to be shown. So, it is not a cinnamon-spices problem... However, it is possible that more people have this rule activated.
