### ISSUE TITLE
User name is link to spices website

### ISSUE THREAD

**Issue by NikoKrause** [clefebvre/cinnamon-spices#31]
@nyrrad 
I've seen this a few times now. There is a user (ore maybe there are users), which have https://cinnamon-spices.linuxmint.com/ as user name. See here https://cinnamon-spices.linuxmint.com/applets/view/161

I think it's [this user](https://github.com/linuxmint/cinnamon-spices-applets/issues/1188), because his/her report seems to be similiar.

**Comment by melmelissa** [comment]
hello

In fact I am the same person.

Alas my problem is still current despite the various updates.
Am i the only one to have this applet bug on Debian. ??
Because on Archlinux, the same applet works well ..
I do not understand the problem ..
Despite my many researches, I remain unanswered and without solution especially ..

**Comment by nyrrad** [comment]
@melmelissa i cant help with the applet error, sorry. This is the issue tracker for the website itself.

But with that you could help me. What method are you using for logging into the spices website? Facebook github or google?

@nikokrause ive seen this same error when the info from the oauth provider isnt avaliable. I have a sneaking suspicion that this is being cause by facebook privacy settings for the user

**Comment by NikoKrause** [comment]
@melmelissa 
Can you help us with this issue and tell us what method did you used for logging into the spices website as you wrote your comment here: https://cinnamon-spices.linuxmint.com/applets/view/161 ?
Did you logged in with Facebook, GitHub or Google+?

**Comment by melmelissa** [comment]
Sorry i had not seen your posts ..
I connect to spice cinnamon with my Google+ account

**Comment by NikoKrause** [comment]
Here's a User `Miguel Bustos`: https://cinnamon-spices.linuxmint.com/applets/view/282
If you click his name, it links to the spices website.

**Comment by nyrrad** [comment]
@nikokrause the site defaults to that when oauth doesnt privide a user link. Which facebook does not(miguel is using fb)  unless you set the privacy setting to allow it. Unless its looking for the wrong endpoint, which is definitely possible.

The google+ bug that this is originally about is tricky though. I'm having trouble reproducing it

**Comment by NikoKrause** [comment]
> the site defaults to that when oauth doesnt privide a user link
Wouldn't it be better to have no link, just the user Name, in such cases?

Maybe @melmelissa can help us? Do you mind telling us, which privacy settings did you set on Google+?

**Comment by nyrrad** [comment]
> Wouldn't it be better to have no link, just the user Name, in such cases?

Yea probably, set it to '#' so it doesn't go anywhere. 

This bug is going to take a backseat until i can get caught up with some others opened recently though. This is the first occurrence I've seen as the name coming through like that, leading me to believe its not the most common.

**Comment by nyrrad** [comment]
I'm able to recreate this bug. Its being called by using a google account that does NOT have a google+ account associated with it.

**Comment by nyrrad** [comment]
Fix pushed, Can see on master
