### ISSUE TITLE
fixed size for applets/desklets/extensions icons

### ISSUE THREAD

**Issue by NikoKrause** [clefebvre/cinnamon-spices#5]
Some icons look squashed, e.g. 
![screenshot-area-2017-02-06-180558](https://cloud.githubusercontent.com/assets/8415124/22657499/024a8b7a-ec97-11e6-8f73-aabf8e9dc3df.png)
Though it uses an 48x48 pixel icon 
![icon](https://cloud.githubusercontent.com/assets/8415124/22657527/1d0831a6-ec97-11e6-94bb-76a4f4ca1c2b.png)

We should define a fixed size (48x48), which should be used by xlet developers. Currently you can find bigger sizes and even some, which are not square size. 
This way it should be easier to show the icons on the website not squashed.

**Comment by MrElectroNick** [comment]
Interesting - layout is a bit currupted in firefox but fine in Chrom(e|ium)
